version: '3.8'

services:
  api:
    build:
      context: .
    container_name: api-tickets
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/db_tickets
      SPRING_DATASOURCE_USERNAME: ticket_user
      SPRING_DATASOURCE_PASSWORD: tickets2025
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_DB: db_tickets
      POSTGRES_PASSWORD: tickets2025
      POSTGRES_USER: ticket_user
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pgdata:/docker-entrypoint-initdb.d/create_db.sh
    ports:
      - 5432:5432

